project:
  type: website
  output-dir: docs

website:
  title: "Murad M."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - about.qmd
      - href: contact.qmd
        text: Contact
  draft-mode: visible

format:
  html:
    theme:
      - cosmo
    include-in-header: 
      - bootstrap-icons.html
      - fontawesome.html
      - head-goatcounter.html
    css: styles.css
    toc: true

